Merge 4.6-fremantle into 4.7

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -683,6 +683,7 @@ CFG_SVG=yes
 CFG_DECLARATIVE=auto
 CFG_WEBKIT=auto # (yes|no|auto)
 CFG_JAVASCRIPTCORE_JIT=auto
+CFG_MAEMO5=no
 
 CFG_GFX_AVAILABLE="linuxfb transformed qvfb vnc multiscreen directfb"
 CFG_GFX_ON="linuxfb multiscreen"
@@ -927,7 +928,7 @@ while [ "$#" -gt 0 ]; do
         ;;
     #Qt style yes options
 
-        -incremental|-qvfb|-profile|-shared|-static|-sm|-xinerama|-xshape|-xvideo|-xsync|-xinput|-reduce-exports|-pch|-separate-debug-info|-stl|-freetype|-xcursor|-xfixes|-xrandr|-xrender|-mitshm|-fontconfig|-xkb|-nis|-qdbus|-dbus|-dbus-linked|-glib|-gstreamer|-gtkstyle|-cups|-iconv|-largefile|-h|-help|-v|-verbose|-debug|-release|-fast|-accessibility|-confirm-license|-gnumake|-framework|-qt3support|-debug-and-release|-exceptions|-cocoa|-carbon|-universal|-prefix-install|-silent|-armfpa|-optimized-qmake|-dwarf2|-reduce-relocations|-sse|-openssl|-openssl-linked|-ptmalloc|-xmlpatterns|-phonon|-phonon-backend|-multimedia|-mediaservice|-audio-backend|-svg|-declarative|-webkit|-javascript-jit|-script|-scripttools|-rpath|-force-pkg-config)
+        -incremental|-qvfb|-profile|-shared|-static|-sm|-xinerama|-xshape|-xvideo|-xsync|-xinput|-reduce-exports|-pch|-separate-debug-info|-stl|-freetype|-xcursor|-xfixes|-xrandr|-xrender|-mitshm|-fontconfig|-xkb|-nis|-qdbus|-dbus|-dbus-linked|-glib|-gstreamer|-gtkstyle|-cups|-iconv|-largefile|-h|-help|-v|-verbose|-debug|-release|-fast|-accessibility|-confirm-license|-gnumake|-framework|-qt3support|-debug-and-release|-exceptions|-cocoa|-carbon|-universal|-prefix-install|-silent|-armfpa|-optimized-qmake|-dwarf2|-reduce-relocations|-sse|-openssl|-openssl-linked|-ptmalloc|-xmlpatterns|-phonon|-phonon-backend|-multimedia|-mediaservice|-audio-backend|-svg|-declarative|-webkit|-javascript-jit|-script|-scripttools|-rpath|-force-pkg-config|-maemo5)
         VAR=`echo $1 | sed "s,^-\(.*\),\1,"`
         VAL=yes
         ;;
@@ -2122,6 +2123,13 @@ while [ "$#" -gt 0 ]; do
             UNKNOWN_OPT=yes
         fi
         ;;
+    maemo5)
+        if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ]; then
+            CFG_MAEMO5="$VAL"
+        else
+            UNKNOWN_OPT=yes
+        fi
+        ;;
     audio-backend)
         if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ]; then
             CFG_AUDIO_BACKEND="$VAL"
@@ -2143,6 +2151,14 @@ done
 if [ "$CFG_QCONFIG" != "full" ] && [ "$CFG_QT3SUPPORT" = "yes" ]; then
     echo "Warning: '-qconfig $CFG_QCONFIG' will disable the qt3support library."
     CFG_QT3SUPPORT="no"
+fi
+
+if [ "$CFG_MAEMO5" != "no" ] && [ "$CFG_QT3SUPPORT" = "yes" ]; then
+    echo "Warning: '-maemo5' will disable the qt3support library."
+    CFG_QT3SUPPORT="no"
+    # Disable ALSA since the PulseAudio ALSA support does not work on the N900
+    # build src/plugins/audio/n900audio instead by default for Maemo 5
+    CFG_ALSA="no"
 fi
 
 # update QT_CONFIG to show our current predefined configuration
@@ -2302,6 +2318,18 @@ if [ "$OPT_SHADOW" = "yes" ]; then
     mkdir -p "$outpath/tools/porting/src"
     rm -f "$outpath/tools/porting/src/q3porting.xml"
     ln -s "$relpath/tools/porting/src/q3porting.xml" "$outpath/tools/porting/src"
+fi
+
+if [ $CFG_MAEMO5 = "yes" ] ; then
+    # if we're within scratchbox, build qmake and friends with the host compiler
+    if [ -z "$PLATFORM" ] && [ -z "$XPLATFORM" ] && [ "$SBOX_UNAME_MACHINE" = "arm" ] ; then
+        XPLATFORM="linux-g++-maemo5"
+        PLATFORM="linux-host-g++"
+        QT_FORCE_PKGCONFIG=yes
+    fi
+    if [ -z "$CFG_ARCH" ] && [ "$SBOX_UNAME_MACHINE" = "arm" ] ; then
+        CFG_ARCH=armv6
+    fi
 fi
 
 # symlink fonts to be able to run application from build directory
@@ -5470,6 +5498,27 @@ if [ "$PLATFORM_X11" = "yes" ]; then
                 CFG_QGTKSTYLE=no
             fi
         fi
+
+        if [ "$CFG_MAEMO5" == "yes" -a "$CFG_QGTKSTYLE" = "yes" ]; then
+            if [ -n "$PKG_CONFIG" ]; then
+                QT_CFLAGS_MAEMO5=`$PKG_CONFIG --cflags hildon-1 2>/dev/null`
+                #QT_LIBS_HILDON=`$PKG_CONFIG --libs gtk+-x11-2.0 hildon-1 2>/dev/null`
+                QMakeVar set QT_CFLAGS_MAEMO5 "$QT_CFLAGS_MAEMO5"
+                #QMakeVar set QT_LIBS_HILDON "$QT_LIBS_HILDON"
+                QMakeVar add styles "maemo5"
+                # Add Hildon to config.h
+                #QCONFIG_FLAGS="$QCONFIG_FLAGS QT_NO_XIM Q_WS_MAEMO_5 Q_OS_FREMANTLE QT_NO_SIZEGRIP QT_NO_PRINTDIALOG QT_NO_PRINTER QT_NO_SYSTEMTRAYICON"
+            else
+                echo "Hildon support cannot be enabled due to functionality test!"
+                echo " Turn on verbose messaging (-v) to $0 to see the final report."
+                echo " If you believe this message is in error you may use the continue"
+                echo " switch (-continue) to $0 to continue."
+                exit 101
+            fi
+        else
+            CFG_MAEMO5="no"
+        fi
+
     elif [ "$CFG_GLIB" = "no" ]; then
         CFG_QGTKSTYLE=no
     fi
@@ -7074,6 +7123,12 @@ if [ "$PLATFORM_QWS" = "yes" ]; then
     done
 fi # QWS
 
+if [ "$CFG_MAEMO5" = "yes" ]; then
+    QT_CONFIG="$QT_CONFIG maemo5"
+    QTCONFIG_CONFIG="$QTCONFIG_CONFIG maemo5"
+    QCONFIG_FLAGS="$QCONFIG_FLAGS QT_NO_XIM Q_WS_MAEMO_5"
+fi
+
 if [ "${CFG_USE_FLOATMATH}" = "yes" ]; then
     QCONFIG_FLAGS="${QCONFIG_FLAGS} QT_USE_MATH_H_FLOATS"
 fi
@@ -7637,6 +7692,7 @@ if [ "$PLATFORM_X11" = "yes" ]; then
     echo "immodule support ....... $CFG_IM"
     echo "GTK theme support ...... $CFG_QGTKSTYLE"
 fi
+[ "$CFG_MAEMO5" != "no" ] && echo "Maemo 5 support ..... $CFG_MAEMO5"
 [ "$CFG_SQL_mysql" != "no" ] && echo "MySQL support .......... $CFG_SQL_mysql"
 [ "$CFG_SQL_psql" != "no" ] && echo "PostgreSQL support ..... $CFG_SQL_psql"
 [ "$CFG_SQL_odbc" != "no" ] && echo "ODBC support ........... $CFG_SQL_odbc"
